version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
networks:
  my-network:
    name: my-network
